using UnityEngine;
using UnityEngine.InputSystem;

/// <summary>
/// DEVICE ABSTRACTION — the single seam between the game and whatever hardware is
/// producing finger force. Everything downstream (NoteHitDetector, InputLogger,
/// PickupIndicator, the whole DDA stack) consumes ONLY normalised [0,1] floats from
/// GetForceForLane, so swapping the input source touches nothing but this file.
///
/// THREE SOURCES, in priority order (PER LANE, evaluated every call):
///   1. Keyboard (either the dev analog simulator or plain binary), whenever the
///      lane's key is currently held down. This is deliberate: keyboard and device
///      can both be "live" at once, and a held key always wins over the device on
///      that lane. In practice the two are never used together — this just makes
///      that assumption explicit instead of silent.
///   2. An external IForceSource (the rehabilitation device), if one is registered
///      and reports IsAvailable, whenever the lane's key is NOT held.
///   3. Neither present → 0.
///
/// (The DEV FORCE SIMULATOR referred to above turns a keyboard key press into
/// realistic ANALOG force instead of a binary 1.0, so the force PI loops can be
/// tuned before hardware is in hand. See the block comment further down.)
///
/// ── WHEN THE DEVICE ARRIVES ─────────────────────────────────────────────────
/// Do NOT edit this file. Write one adapter class implementing IForceSource and
/// register it (see the interface docs). That keeps the keyboard path intact for
/// testing and makes the swap a single line.
/// </summary>
public class InputManagerScript : MonoBehaviour
{
    public static InputManagerScript Instance;

    // ══════════════════════════════════════════════════════════════════════
    //  DEVICE SEAM
    // ══════════════════════════════════════════════════════════════════════

    /// <summary>
    /// Implemented by the hardware adapter. Register with
    /// InputManagerScript.RegisterForceSource(mySource) from the adapter's Awake.
    /// While a source is registered AND reports IsAvailable, it takes priority over
    /// every keyboard path — no other file needs to know it exists.
    ///
    /// The adapter is responsible for NORMALISATION: whatever raw units the device
    /// reports (ADC counts, newtons, grams) must come out of GetForce as [0,1],
    /// where 1.0 is that finger's usable saturation point. The game has no way to
    /// discover the device's scale on its own.
    /// </summary>
    public interface IForceSource
    {
        bool  IsAvailable { get; }
        float GetForce(int laneIndex);
        string SourceName { get; }
    }

    static IForceSource _deviceSource;

    public static void RegisterForceSource(IForceSource src)
    {
        _deviceSource = src;
        Debug.Log($"[InputManager] Force source registered: {src?.SourceName ?? "null"}");
    }

    public static void ClearForceSource() => _deviceSource = null;

    /// <summary>True when a hardware source is registered and reporting available.</summary>
    public static bool DeviceConnected => _deviceSource != null && _deviceSource.IsAvailable;

    public static string ActiveSourceName =>
        DeviceConnected ? _deviceSource.SourceName : "Keyboard (Q/W/E/R)";

    // ══════════════════════════════════════════════════════════════════════
    //  KEYBOARD
    // ══════════════════════════════════════════════════════════════════════

    // Keyboard keys used for simulation, one per lane (index, middle, ring, pinky).
    private static readonly Key[] laneKeys = { Key.Q, Key.W, Key.E, Key.R };

    public const int LaneCount = 4;

    // ══════════════════════════════════════════════════════════════════════
    //  DEV FORCE SIMULATOR
    // ══════════════════════════════════════════════════════════════════════
    //
    // WHY THIS EXISTS
    //   A keyboard key is binary: 1.0 or 0.0. Fed into the force pipeline that makes
    //   forceMargin take exactly two values, which is useless for tuning a PI loop
    //   that is supposed to regulate a continuous, noisy signal. This simulator turns
    //   a key press into a plausible analog force so the four force loops can be
    //   tuned, step-tested and stress-tested against noise BEFORE the hardware exists.
    //
    // WHY THE NOISE IS SAMPLED PER PRESS, NOT PER FRAME
    //   This is the important design decision. If a fresh Gaussian sample were drawn
    //   every frame, then fMax — the max over ~50 samples in a press — would converge
    //   on roughly mean + 3σ instead of the mean. Raising the noise slider would then
    //   RAISE the apparent force, and the force loop would be tuned against a
    //   systematically biased plant. Instead one base force is drawn at press onset
    //   and held for the whole press, exactly as a real finger produces one intended
    //   effort per press. Turning up noise then widens the press-to-press SPREAD with
    //   the mean unchanged, which is the thing the estimator's EMA actually has to
    //   filter.
    //
    // WHY THERE IS STILL A WITHIN-PRESS COMPONENT
    //   With a perfectly flat press, fMax == fAvg, and Tap notes (which use fMax)
    //   would be indistinguishable from Hold notes (which use fAvg) — hiding a real
    //   distinction in the pipeline. The attack ramp and the slow tremor restore
    //   fMax > fAvg with a realistic gap, so both branches of NoteResolver's
    //   reference-force choice get exercised. Set both to 0 for a flat-top press.
    //
    // The simulator is a DEV TOOL. Compiled out of release builds entirely.

    [Header("── Dev force simulator (keyboard analog force) ──")]
    [Tooltip("Turn a binary key press into an analog force. OFF = legacy behaviour " +
             "(key down = 1.0). Ignored entirely when a hardware source is connected.")]
    public bool simulateAnalogForce = false;

    [Tooltip("Mean force a press produces, in normalised sensor units [0,1]. Compare " +
             "against GameDifficulty.requiredForce[lane] (τ_ℓ): the force margin the " +
             "loops regulate is roughly this minus τ_ℓ.")]
    [Range(0f, 1f)] public float simulatedForce = 0.6f;

    [Tooltip("Standard deviation σ of the press-to-press force spread. One sample is " +
             "drawn per press from N(simulatedForce, σ²) and held for that whole press. " +
             "0 = every press identical. ~0.05 = a steady player, ~0.15 = an erratic or " +
             "tremulous one. This is the knob for testing how well the tuned gains cope " +
             "with a noisy measurement.")]
    [Range(0f, 0.4f)] public float simulatedForceNoise = 0f;

    [Tooltip("Seconds for force to ramp from 0 to the press's base value at onset. " +
             "Makes fAvg fall below fMax the way a real press does. 0 = instant.")]
    [Range(0f, 0.5f)] public float simulatedAttackSeconds = 0.08f;

    [Tooltip("Within-press wobble, as a FRACTION of the noise σ above. Smooth (Perlin), " +
             "not white, so it reads as tremor rather than sensor hash. 0 = flat-top press.")]
    [Range(0f, 2f)] public float simulatedTremorFraction = 0.35f;

    [Tooltip("Tremor frequency in Hz.")]
    [Range(0.1f, 12f)] public float simulatedTremorHz = 3f;

    [Tooltip("Per-lane multiplier on the mean force, so you can simulate one weak " +
             "finger and confirm the four loops really do diverge independently. " +
             "Leave at 1,1,1,1 for a symmetric hand.")]
    public float[] simulatedLaneScale = { 1f, 1f, 1f, 1f };

    // ---- per-lane simulator state ----
    readonly bool[]  _simPressed   = new bool[LaneCount];
    readonly float[] _simBaseForce = new float[LaneCount];
    readonly float[] _simPressTime = new float[LaneCount];
    readonly float[] _simSeed      = new float[LaneCount];

    /// <summary>Last value returned per lane — read by HUDs for display only.</summary>
    readonly float[] _lastForce = new float[LaneCount];
    public float LastForce(int lane) =>
        (lane >= 0 && lane < LaneCount) ? _lastForce[lane] : 0f;

    // ══════════════════════════════════════════════════════════════════════

    private void Awake()
    {
        Instance = this;

        // Defensive: an inspector edit can leave this array the wrong length.
        if (simulatedLaneScale == null || simulatedLaneScale.Length != LaneCount)
        {
            var scale = new float[LaneCount];
            for (int i = 0; i < LaneCount; i++)
                scale[i] = (simulatedLaneScale != null && i < simulatedLaneScale.Length)
                           ? simulatedLaneScale[i] : 1f;
            simulatedLaneScale = scale;
        }

        for (int i = 0; i < LaneCount; i++) _simSeed[i] = Random.Range(0f, 1000f);
    }

    /// <summary>
    /// Returns a normalised force value [0, 1] for the given lane.
    ///
    /// SAFE TO CALL MANY TIMES PER FRAME. NoteHitDetector, InputLogger and
    /// PickupIndicator all poll this independently, so the simulator's state
    /// transitions are edge-triggered and idempotent within a frame: the first call
    /// after a key goes down draws the base force, every later call in that same
    /// frame sees _simPressed already true and returns a value derived from the same
    /// base. Without that, the three consumers would each see a different force for
    /// the same physical press.
    /// </summary>
    public float GetForceForLane(int laneIndex)
    {
        if (laneIndex < 0 || laneIndex >= LaneCount) return 0f;

        float f = ReadRaw(laneIndex);
        _lastForce[laneIndex] = f;
        return f;
    }

    float ReadRaw(int laneIndex)
    {
        var keyboard = Keyboard.current;
        bool down = keyboard != null && keyboard[laneKeys[laneIndex]].isPressed;

        // ---- 1. keyboard, only while this lane's key is actually held ----
        // Keyboard wins over the device whenever it's live, so a player can always
        // override or test a single lane from the keyboard without unplugging the
        // device. When the key is up, we fall through to the device below instead
        // of returning 0 here.
        if (down)
        {
#if UNITY_EDITOR || DEVELOPMENT_BUILD
            if (simulateAnalogForce) return SimulatedForce(laneIndex, true);
#endif
            _simPressed[laneIndex] = true;
            return 1.0f;
        }

        // Key just released (or was never down) — keep simulator edge-state coherent
        // even while the device is supplying the value, so a later key press still
        // edge-triggers a fresh base force draw instead of resuming a stale press.
#if UNITY_EDITOR || DEVELOPMENT_BUILD
        if (simulateAnalogForce) SimulatedForce(laneIndex, false);
        else _simPressed[laneIndex] = false;
#else
        _simPressed[laneIndex] = false;
#endif

        // ---- 2. hardware device, if present and reporting fresh data ----
        if (_deviceSource != null && _deviceSource.IsAvailable)
            return Mathf.Clamp01(_deviceSource.GetForce(laneIndex));

        // ---- 3. nothing pressed, no device ----
        return 0f;
    }

#if UNITY_EDITOR || DEVELOPMENT_BUILD
    float SimulatedForce(int lane, bool down)
    {
        if (!down)
        {
            _simPressed[lane] = false;
            return 0f;
        }

        // Rising edge: draw ONE base force for this entire press. See the block
        // comment above for why this is per-press and not per-frame.
        if (!_simPressed[lane])
        {
            _simPressed[lane]   = true;
            _simPressTime[lane] = Time.time;
            _simSeed[lane]      = Random.Range(0f, 1000f);

            float scale = (simulatedLaneScale != null && lane < simulatedLaneScale.Length)
                          ? simulatedLaneScale[lane] : 1f;
            float mean  = Mathf.Clamp01(simulatedForce * scale);

            _simBaseForce[lane] = Mathf.Clamp01(SampleGaussian(mean, simulatedForceNoise));
        }

        float f       = _simBaseForce[lane];
        float elapsed = Time.time - _simPressTime[lane];

        // Attack ramp — gives fAvg < fMax, so Tap (fMax) and Hold (fAvg) differ.
        if (simulatedAttackSeconds > 1e-4f)
            f *= Mathf.Clamp01(elapsed / simulatedAttackSeconds);

        // Smooth tremor — Perlin, so successive frames correlate like a real hand
        // rather than hashing white noise into fMax.
        if (simulatedTremorFraction > 1e-4f && simulatedForceNoise > 1e-4f)
        {
            float amp = simulatedForceNoise * simulatedTremorFraction;
            float n   = Mathf.PerlinNoise(_simSeed[lane] + elapsed * simulatedTremorHz, 0.5f);
            f += amp * (n - 0.5f) * 2f;
        }

        return Mathf.Clamp01(f);
    }

    /// <summary>Box–Muller. UnityEngine.Random is uniform; press force is not.</summary>
    static float SampleGaussian(float mean, float sigma)
    {
        if (sigma <= 1e-6f) return mean;
        float u1 = Mathf.Max(1e-6f, Random.value);
        float u2 = Random.value;
        float z  = Mathf.Sqrt(-2f * Mathf.Log(u1)) * Mathf.Cos(2f * Mathf.PI * u2);
        return mean + sigma * z;
    }
#endif
}
